"""Reviewed, browser-safe practice tasks for every Python lesson."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Exercise:
    lesson: int
    prompt: str
    starter: str
    solution: str
    explanation: str
    tests: tuple[tuple[str, str], ...]

    def as_json(self) -> dict[str, object]:
        return {
            "lesson": self.lesson, "prompt": self.prompt, "starter": self.starter,
            "solution": self.solution, "explanation": self.explanation,
            "tests": [{"label": label, "check": check} for label, check in self.tests],
        }


EXERCISES = (
    Exercise(1, "Crie media_duas(a, b), que devolve a média aritmética de dois números.",
             "def media_duas(a, b):\n    # calcule e devolva a média\n    pass",
             "def media_duas(a, b):\n    return (a + b) / 2",
             "Some as duas entradas e divida por 2. O retorno permite que outra função use a média.",
             (("notas 6 e 8", "media_duas(6, 8) == 7"), ("duas notas zero", "media_duas(0, 0) == 0"), ("valores negativos", "media_duas(-2, 2) == 0"))),
    Exercise(2, "Crie procurar(titulos, alvo), que devolve o índice da primeira ocorrência ou -1.",
             "def procurar(titulos, alvo):\n    # percorra a lista sem alterar a entrada\n    pass",
             "def procurar(titulos, alvo):\n    for indice, titulo in enumerate(titulos):\n        if titulo == alvo:\n            return indice\n    return -1",
             "O laço olha cada posição. Só devolvemos -1 após percorrer tudo sem encontrar.",
             (("primeiro item", "procurar(['A', 'B'], 'A') == 0"), ("último item", "procurar(['A', 'B'], 'B') == 1"), ("ausente", "procurar(['A'], 'Z') == -1"), ("vazio", "procurar([], 'Z') == -1"))),
    Exercise(3, "Crie classificar(nota): 'aprovado' para nota >= 7; caso contrário, 'revisar'.",
             "def classificar(nota):\n    pass",
             "def classificar(nota):\n    if nota >= 7:\n        return 'aprovado'\n    return 'revisar'",
             "O teste no limite 7 distingue >= de >. Cada ramo devolve um texto claro.",
             (("abaixo do limite", "classificar(6.9) == 'revisar'"), ("exatamente no limite", "classificar(7) == 'aprovado'"), ("acima do limite", "classificar(9) == 'aprovado'"))),
    Exercise(4, "Crie saudacao(nome), que devolve 'Olá, NOME!' usando o nome recebido.",
             "def saudacao(nome):\n    pass",
             "def saudacao(nome):\n    return f'Olá, {nome}!'",
             "Uma f-string insere o argumento. A função não depende de variável global.",
             (("nome simples", "saudacao('Ana') == 'Olá, Ana!'"), ("nome composto", "saudacao('Ana Maria') == 'Olá, Ana Maria!'"))),
    Exercise(5, "Crie total_itens(a, b, c), que soma três preços numéricos.",
             "def total_itens(a, b, c):\n    pass",
             "def total_itens(a, b, c):\n    return a + b + c",
             "Os argumentos já são números. A soma é devolvida, não apenas impressa.",
             (("três itens", "total_itens(2, 3, 4) == 9"), ("valores zero", "total_itens(0, 0, 0) == 0"), ("decimal", "abs(total_itens(1.5, 2, 0) - 3.5) < 1e-9"))),
    Exercise(6, "Crie dobro_texto(texto): converta um inteiro textual e devolva seu dobro.",
             "def dobro_texto(texto):\n    pass",
             "def dobro_texto(texto):\n    quantidade = int(texto)\n    return quantidade * 2",
             "A conversão ocorre antes da multiplicação; multiplicar a string repetiria caracteres.",
             (("texto 7", "dobro_texto('7') == 14"), ("zero", "dobro_texto('0') == 0"), ("espaços", "dobro_texto(' 4 ') == 8"))),
    Exercise(7, "Crie situacao(nota): fora de 0 a 10 é 'inválida'; >= 7 é 'aprovado'; demais, 'revisar'.",
             "def situacao(nota):\n    pass",
             "def situacao(nota):\n    if nota < 0 or nota > 10:\n        return 'inválida'\n    if nota >= 7:\n        return 'aprovado'\n    return 'revisar'",
             "Valide primeiro. Depois os intervalos restantes não se sobrepõem.",
             (("abaixo de zero", "situacao(-1) == 'inválida'"), ("limite sete", "situacao(7) == 'aprovado'"), ("revisão", "situacao(6.9) == 'revisar'"), ("acima de dez", "situacao(11) == 'inválida'"))),
    Exercise(8, "Implemente soma_ate(n) com while: 1 + ... + n; para n=0, devolva 0.",
             "def soma_ate(n):\n    total = 0\n    # use while\n    return total",
             "def soma_ate(n):\n    total = 0\n    atual = 1\n    while atual <= n:\n        total += atual\n        atual += 1\n    return total",
             "O contador avança em cada volta e a soma começa em zero.",
             (("zero", "soma_ate(0) == 0"), ("um", "soma_ate(1) == 1"), ("quatro", "soma_ate(4) == 10"))),
    Exercise(9, "Conte múltiplos de 3 no intervalo fechado [inicio, fim].",
             "def contar_multiplos_3(inicio, fim):\n    pass",
             "def contar_multiplos_3(inicio, fim):\n    quantidade = 0\n    for numero in range(inicio, fim + 1):\n        if numero % 3 == 0:\n            quantidade += 1\n    return quantidade",
             "Somar 1 ao fim compensa o limite exclusivo de range. Intervalo invertido fica vazio.",
             (("de 1 a 10", "contar_multiplos_3(1, 10) == 3"), ("limite três", "contar_multiplos_3(3, 3) == 1"), ("invertido", "contar_multiplos_3(5, 2) == 0"))),
    Exercise(10, "Crie iniciais(nome) para duas ou mais palavras, ignorando espaços nas pontas.",
             "def iniciais(nome):\n    pass",
             "def iniciais(nome):\n    palavras = nome.split()\n    return ''.join(palavra[0].upper() for palavra in palavras)",
             "split sem argumento ignora espaços extras; cada primeira letra vira maiúscula.",
             (("nome composto", "iniciais('Ana Maria') == 'AM'"), ("espaços extras", "iniciais('  Ada   Lovelace ') == 'AL'"), ("vazio", "iniciais('  ') == ''"))),
    Exercise(11, "Crie maior(valores), que devolve o maior número ou None para lista vazia.",
             "def maior(valores):\n    pass",
             "def maior(valores):\n    if not valores:\n        return None\n    return max(valores)",
             "O caso vazio precisa ser tratado antes de max. A entrada não é modificada.",
             (("lista vazia", "maior([]) is None"), ("números positivos", "maior([2, 8, 3]) == 8"), ("negativos", "maior([-4, -2]) == -2"))),
    Exercise(12, "Conte cada palavra da lista, sem diferenciar maiúsculas e minúsculas.",
             "def contar_palavras(palavras):\n    pass",
             "def contar_palavras(palavras):\n    contagens = {}\n    for palavra in palavras:\n        chave = palavra.casefold()\n        contagens[chave] = contagens.get(chave, 0) + 1\n    return contagens",
             "casefold normaliza a comparação; get inicia em zero sem criar chave antes.",
             (("vazio", "contar_palavras([]) == {}"), ("repetidas", "contar_palavras(['A', 'a', 'B']) == {'a': 2, 'b': 1}"))),
    Exercise(13, "Frete: 0 se total >= 100; senão 10 se distância <= 20; senão 20.",
             "def frete(total, distancia):\n    pass",
             "def frete(total, distancia):\n    if total >= 100:\n        return 0\n    if distancia <= 20:\n        return 10\n    return 20",
             "A primeira regra tem prioridade. Teste os dois limites, 100 e 20.",
             (("grátis no limite", "frete(100, 50) == 0"), ("perto", "frete(99, 20) == 10"), ("longe", "frete(99, 21) == 20"))),
    Exercise(14, "Calcule fatorial(n) para inteiro não negativo; n=0 deve devolver 1.",
             "def fatorial(n):\n    pass",
             "def fatorial(n):\n    if n < 0:\n        raise ValueError('n negativo')\n    if n == 0:\n        return 1\n    return n * fatorial(n - 1)",
             "O caso base é 0! = 1; cada chamada aproxima n desse caso.",
             (("zero", "fatorial(0) == 1"), ("um", "fatorial(1) == 1"), ("cinco", "fatorial(5) == 120"), ("negativo", "_raises_value_error(fatorial, -1)"))),
    Exercise(15, "Crie hipotenusa(a, b) usando math.hypot.",
             "import math\n\ndef hipotenusa(a, b):\n    pass",
             "import math\n\ndef hipotenusa(a, b):\n    return math.hypot(a, b)",
             "A biblioteca padrão já implementa a operação numérica com estabilidade.",
             (("triângulo 3-4-5", "abs(hipotenusa(3, 4) - 5) < 1e-9"), ("origem", "hipotenusa(0, 0) == 0"))),
    Exercise(16, "Receba JSON com lista 'valores' e devolva sua soma.",
             "import json\n\ndef somar_json(texto):\n    pass",
             "import json\n\ndef somar_json(texto):\n    dados = json.loads(texto)\n    return sum(dados['valores'])",
             "json.loads interpreta o texto; a função soma os números da chave definida.",
             (("três números", "somar_json('{\"valores\": [2, 3, 4]}') == 9"), ("lista vazia", "somar_json('{\"valores\": []}') == 0"))),
    Exercise(17, "Divida a por b; se b for zero, devolva a string 'impossível'.",
             "def dividir(a, b):\n    pass",
             "def dividir(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return 'impossível'",
             "Capturamos só a falha esperada; outros bugs continuam visíveis.",
             (("divisão comum", "dividir(8, 2) == 4"), ("por zero", "dividir(8, 0) == 'impossível'"), ("negativo", "dividir(-6, 2) == -3"))),
    Exercise(18, "Corrija a fronteira: desconto de 10% vale quando total é pelo menos 100.",
             "def total_com_desconto(total):\n    if total > 100:  # há um bug neste limite\n        return total * 0.9\n    return total",
             "def total_com_desconto(total):\n    if total >= 100:\n        return total * 0.9\n    return total",
             "O teste exatamente em 100 expõe a diferença entre > e >=.",
             (("antes do limite", "total_com_desconto(99) == 99"), ("no limite", "total_com_desconto(100) == 90"), ("acima", "total_com_desconto(200) == 180"))),
    Exercise(19, "Implemente Carteira(saldo) e depositar(valor), devolvendo o novo saldo; negativo é inválido.",
             "class Carteira:\n    def __init__(self, saldo=0):\n        pass\n\n    def depositar(self, valor):\n        pass",
             "class Carteira:\n    def __init__(self, saldo=0):\n        self.saldo = saldo\n\n    def depositar(self, valor):\n        if valor < 0:\n            raise ValueError('depósito negativo')\n        self.saldo += valor\n        return self.saldo",
             "Cada instância guarda seu saldo; a validação ocorre antes da mudança.",
             (("depósito", "Carteira(10).depositar(5) == 15"), ("saldo independente", "_carteiras_independentes(Carteira)"), ("negativo", "_raises_value_error(Carteira(0).depositar, -1)"))),
    Exercise(20, "Crie DescontoFixo e DescontoPercentual, ambos com aplicar(preco).",
             "class DescontoFixo:\n    def __init__(self, valor):\n        pass\n    def aplicar(self, preco):\n        pass\n\nclass DescontoPercentual:\n    def __init__(self, taxa):\n        pass\n    def aplicar(self, preco):\n        pass",
             "class DescontoFixo:\n    def __init__(self, valor):\n        self.valor = valor\n    def aplicar(self, preco):\n        return preco - self.valor\n\nclass DescontoPercentual:\n    def __init__(self, taxa):\n        self.taxa = taxa\n    def aplicar(self, preco):\n        return preco * (1 - self.taxa)",
             "As duas classes compartilham comportamento esperado, sem precisar de herança.",
             (("fixo", "DescontoFixo(10).aplicar(100) == 90"), ("percentual", "DescontoPercentual(0.1).aplicar(100) == 90"), ("polimorfismo", "[d.aplicar(100) for d in [DescontoFixo(5), DescontoPercentual(.2)]] == [95, 80]"))),
    Exercise(21, "Crie dataclass Coordenada(x, y) e função distancia_origem(ponto).",
             "from dataclasses import dataclass\n\n@dataclass\nclass Coordenada:\n    x: float\n    y: float\n\ndef distancia_origem(ponto):\n    pass",
             "from dataclasses import dataclass\nimport math\n\n@dataclass\nclass Coordenada:\n    x: float\n    y: float\n\ndef distancia_origem(ponto):\n    return math.hypot(ponto.x, ponto.y)",
             "A dataclass guarda campos nomeados; math.hypot calcula a distância.",
             (("origem", "distancia_origem(Coordenada(0, 0)) == 0"), ("triângulo", "distancia_origem(Coordenada(3, 4)) == 5"))),
    Exercise(22, "Crie gerador quadrados(n), que produz 0² até (n-1)² usando yield.",
             "def quadrados(n):\n    # use yield dentro de um laço\n    pass",
             "def quadrados(n):\n    for valor in range(n):\n        yield valor * valor",
             "yield produz um elemento por vez. list materializa apenas no teste.",
             (("vazio", "list(quadrados(0)) == []"), ("quatro", "list(quadrados(4)) == [0, 1, 4, 9]"))),
    Exercise(23, "Use with e io.StringIO para contar linhas de um texto.",
             "import io\n\ndef contar_linhas(texto):\n    pass",
             "import io\n\ndef contar_linhas(texto):\n    with io.StringIO(texto) as arquivo:\n        return sum(1 for _ in arquivo)",
             "O gerenciador fecha o recurso. O laço conta linhas existentes.",
             (("vazio", "contar_linhas('') == 0"), ("duas linhas", "contar_linhas('a\\nb') == 2"), ("linha final", "contar_linhas('a\\n') == 1"))),
    Exercise(24, "Crie async resultado_duplo(n): espere com asyncio.sleep(0) e devolva n*2.",
             "import asyncio\n\nasync def resultado_duplo(n):\n    pass",
             "import asyncio\n\nasync def resultado_duplo(n):\n    await asyncio.sleep(0)\n    return n * 2",
             "await cede controle ao loop; o teste executa a coroutine com asyncio.run.",
             (("dobro de quatro", "await _await_result(resultado_duplo(4), 8)"), ("zero", "await _await_result(resultado_duplo(0), 0)"))),
    Exercise(25, "Use Counter para devolver a quantidade de cada cor da lista.",
             "from collections import Counter\n\ndef contar_cores(cores):\n    pass",
             "from collections import Counter\n\ndef contar_cores(cores):\n    return dict(Counter(cores))",
             "Counter conta itens; dict torna a saída um mapeamento comum.",
             (("vazio", "contar_cores([]) == {}"), ("repetição", "contar_cores(['azul', 'azul', 'verde']) == {'azul': 2, 'verde': 1}"))),
    Exercise(26, "Use Decimal para aplicar taxa e devolver texto com duas casas.",
             "from decimal import Decimal\n\ndef aplicar_taxa(preco, taxa):\n    pass",
             "from decimal import Decimal\n\ndef aplicar_taxa(preco, taxa):\n    total = Decimal(preco) * (1 + Decimal(taxa))\n    return f'{total:.2f}'",
             "Receba textos decimais para não carregar aproximação de float.",
             (("dez por cento", "aplicar_taxa('10.00', '0.10') == '11.00'"), ("taxa zero", "aplicar_taxa('3.50', '0') == '3.50'"))),
    Exercise(27, "Crie aviso(tarefas): devolva 'lista vazia' se não houver tarefas; senão, a quantidade em texto.",
             "def aviso(tarefas):\n    pass",
             "def aviso(tarefas):\n    if not tarefas:\n        return 'lista vazia'\n    return f'{len(tarefas)} tarefa(s)'",
             "A função monta a mensagem; uma camada externa decide registrá-la em logging.",
             (("sem tarefas", "aviso([]) == 'lista vazia'"), ("duas tarefas", "aviso(['a', 'b']) == '2 tarefa(s)'"))),
    Exercise(28, "Some duas listas numéricas posição a posição, como um vetor.",
             "def somar_vetores(a, b):\n    pass",
             "def somar_vetores(a, b):\n    if len(a) != len(b):\n        raise ValueError('tamanhos diferentes')\n    return [x + y for x, y in zip(a, b)]",
             "Verificar shapes evita perder elementos, pois zip pararia na lista menor.",
             (("dois valores", "somar_vetores([1, 2], [3, 4]) == [4, 6]"), ("vazio", "somar_vetores([], []) == []"), ("tamanhos", "_raises_value_error(somar_vetores, [1], [1, 2])"))),
    Exercise(29, "Agrupe vendas por produto a partir de lista de dicionários.",
             "def totais_por_produto(vendas):\n    pass",
             "def totais_por_produto(vendas):\n    totais = {}\n    for venda in vendas:\n        produto = venda['produto']\n        totais[produto] = totais.get(produto, 0) + venda['valor']\n    return totais",
             "A versão com dicionário explicita a operação que groupby fará no pandas.",
             (("sem vendas", "totais_por_produto([]) == {}"), ("repetidas", "totais_por_produto([{'produto':'A','valor':10},{'produto':'A','valor':20},{'produto':'B','valor':5}]) == {'A':30,'B':5}"))),
    Exercise(30, "Devolva duas listas: rótulos e alturas para um gráfico de barras.",
             "def dados_grafico(totais):\n    pass",
             "def dados_grafico(totais):\n    rotulos = sorted(totais)\n    alturas = [totais[rotulo] for rotulo in rotulos]\n    return rotulos, alturas",
             "Ordenar rótulos dá saída estável e mantém cada altura ligada à sua categoria.",
             (("duas categorias", "dados_grafico({'B':15,'A':30}) == (['A','B'],[30,15])"), ("vazio", "dados_grafico({}) == ([],[])"))),
    Exercise(31, "Extraia títulos não vazios de um JSON com campo 'itens'.",
             "import json\n\ndef extrair_titulos(texto):\n    pass",
             "import json\n\ndef extrair_titulos(texto):\n    dados = json.loads(texto)\n    return [item['titulo'] for item in dados['itens'] if item.get('titulo')]",
             "A regra é independente da rede; HTTPX apenas obteria o JSON.",
             (("títulos presentes", "extrair_titulos('{\"itens\":[{\"titulo\":\"A\"},{\"titulo\":\"\"},{\"x\":1}]}') == ['A']"), ("vazio", "extrair_titulos('{\"itens\":[]}') == []"))),
    Exercise(32, "Crie preço_final(preco, taxa) que uma rota de API poderia chamar.",
             "def preco_final(preco, taxa):\n    pass",
             "def preco_final(preco, taxa):\n    if preco < 0 or taxa < 0:\n        raise ValueError('entrada negativa')\n    return preco * (1 + taxa)",
             "A regra fica testável fora do servidor; a rota traduziria HTTP para chamada.",
             (("taxa simples", "abs(preco_final(100, .1) - 110) < 1e-9"), ("sem taxa", "preco_final(20, 0) == 20"), ("inválido", "_raises_value_error(preco_final, -1, .1)"))),
    Exercise(33, "Devolva títulos das tarefas com status 'pendente', sem alterar a lista.",
             "def tarefas_pendentes(tarefas):\n    pass",
             "def tarefas_pendentes(tarefas):\n    return [t['titulo'] for t in tarefas if t.get('status') == 'pendente']",
             "O bot pode usar a lista resultante para preparar relatório antes de qualquer ação externa.",
             (("mistas", "tarefas_pendentes([{'titulo':'A','status':'pendente'},{'titulo':'B','status':'feito'}]) == ['A']"), ("vazio", "tarefas_pendentes([]) == []"))),
    Exercise(34, "Calcule acurácia entre listas de respostas e previsões; para vazio, devolva None.",
             "def acuracia(reais, previstos):\n    pass",
             "def acuracia(reais, previstos):\n    if len(reais) != len(previstos):\n        raise ValueError('tamanhos diferentes')\n    if not reais:\n        return None\n    acertos = sum(a == b for a, b in zip(reais, previstos))\n    return acertos / len(reais)",
             "A métrica divide acertos pelo total e explicita casos sem dado e tamanhos diferentes.",
             (("metade", "acuracia([1,0],[1,1]) == .5"), ("todos", "acuracia(['a','b'],['a','b']) == 1"), ("vazio", "acuracia([],[]) is None"))),
    Exercise(35, "Classificador manual: valores >= limiar recebem 1; os demais, 0.",
             "def prever_limiar(valores, limiar):\n    pass",
             "def prever_limiar(valores, limiar):\n    return [1 if valor >= limiar else 0 for valor in valores]",
             "A regra simples é uma linha de base interpretável para comparar com scikit-learn.",
             (("fronteira", "prever_limiar([2,3,4],3) == [0,1,1]"), ("vazio", "prever_limiar([],3) == []"))),
    Exercise(36, "Devolva matriz de confusão binária como (VP, FP, VN, FN).",
             "def confusao(reais, previstos):\n    pass",
             "def confusao(reais, previstos):\n    if len(reais) != len(previstos):\n        raise ValueError('tamanhos diferentes')\n    vp = fp = vn = fn = 0\n    for real, previsto in zip(reais, previstos):\n        if real == 1 and previsto == 1: vp += 1\n        elif real == 0 and previsto == 1: fp += 1\n        elif real == 0 and previsto == 0: vn += 1\n        else: fn += 1\n    return vp, fp, vn, fn",
             "Cada combinação de real e previsto ocupa uma célula; o total deve igualar número de casos.",
             (("quatro casos", "confusao([1,0,0,1],[1,1,0,0]) == (1,1,1,1)"), ("vazio", "confusao([],[]) == (0,0,0,0)"))),
    Exercise(37, "Filtre tarefas de uma lista por id, devolvendo a primeira ou None.",
             "def buscar_tarefa(tarefas, identificador):\n    pass",
             "def buscar_tarefa(tarefas, identificador):\n    for tarefa in tarefas:\n        if tarefa['id'] == identificador:\n            return tarefa\n    return None",
             "A mesma regra pode virar SELECT parametrizado em SQLite.",
             (("encontrada", "buscar_tarefa([{'id':1,'titulo':'A'}],1) == {'id':1,'titulo':'A'}"), ("ausente", "buscar_tarefa([{'id':1}],2) is None"))),
    Exercise(38, "Resumo de operação: conte concluídas e pendentes numa lista de tarefas.",
             "def resumo_operacao(tarefas):\n    pass",
             "def resumo_operacao(tarefas):\n    return {'concluidas': sum(t.get('status') == 'feito' for t in tarefas),\n            'pendentes': sum(t.get('status') == 'pendente' for t in tarefas)}",
             "A função de regra é pura; API, banco e logs podem usá-la sem duplicar cálculo.",
             (("mistas", "resumo_operacao([{'status':'feito'},{'status':'pendente'}]) == {'concluidas':1,'pendentes':1}"), ("vazio", "resumo_operacao([]) == {'concluidas':0,'pendentes':0}"))),
    Exercise(39, "Projeto final: devolva total de despesas não negativas; rejeite valor negativo.",
             "def total_despesas(valores):\n    pass",
             "def total_despesas(valores):\n    if any(valor < 0 for valor in valores):\n        raise ValueError('despesa negativa')\n    return sum(valores)",
             "A função pode ser testada separadamente e depois usada por CLI, API ou relatório.",
             (("vazio", "total_despesas([]) == 0"), ("valores", "total_despesas([10, 5, 2]) == 17"), ("negativo", "_raises_value_error(total_despesas, [1, -2])"))),
)
